<html>
<body style="width:100%;height:100%">
<table border="1" cellspacing="0" cellpadding="0" style="width:100%;height:100%">
    <tr>
        <td colspan="2">
            $layout/header()$
        </td>
    </tr>
    <tr>
        <td>
            $layout/menu()$
        </td>
        <td>
            $body$
        </td>
    </tr>
    <tr>
        <td colspan="2">
            $layout/footer()$
        </td>
    </tr>
</table>
</body>
</html>