<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title></title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Place favicon.ico and apple-touch-icon.png in the root directory -->

    <link rel="stylesheet" type="text/css" href="./resources/css/normalize.css">
    <link rel="stylesheet" type="text/css" href="./resources/css/main.css">
    <link rel="stylesheet" type="text/css" href="./resources/css/colours.css">
    <link rel="stylesheet" type="text/css" href="./resources/css/gallery/gallery.css">
    <link rel="stylesheet" type="text/css" href="./resources/css/lightbox.css">
    <!--<link rel="stylesheet" type="text/css" href="./resources/css/screen.css">-->
    <!--<script src="js/vendor/modernizr-2.6.2.min.js"></script>-->

    <script src="/resources/js/jquery-1.10.2.min.js"></script>
    <script src="/resources/js/lightbox-2.6.min.js"></script>
    <script src="/resources/js/gallery.js"></script>
</head>