$constantAssets/docType()$
$homepage/homeHeader()$

<body xmlns="http://www.w3.org/1999/html" xmlns="http://www.w3.org/1999/html" xmlns="http://www.w3.org/1999/html">
<!--[if lt IE 7]>
<p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
<![endif]-->

<script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
<script>window.jQuery || document.write('<script src="js/vendor/jquery-1.10.2.min.js"><\/script>')</script>
<script src="/resources/js/plugins.js"></script>
<script src="/resources/js/homePage.js"></script>

<!-- Google Analytics: change UA-XXXXX-X to be your site's ID. -->

<div id="wrapper">
    <div id="headerwrap">
        <div id="header">
        </div>
    </div>
$constantAssets/topNavigation()$
$constantAssets/facebookColumn()$
    <div id="contentwrap">
        <div id="leftContent">
            <p>
                <span>Jazzy Jungle is a small family run play centre where we offer a friendly, reasonably priced service.</span><br /><br />
                <span>We aim to enable families to visit regularly, meet up or find new friends and to give the children an opportunity to do the same whilst enjoying the free-play experience in a safe environment.</span><br /><br />
                <span>Our very own host, Jazzy the Friendly Tiger can regularly be seen presenting birthday cakes in our party room.</span><br /><br />
            </p>
            <div class="leftcontentcontainerimage">
            <a href="/resources/images/jazzy01.gif" data-lightbox="jazzy01" title="My caption" data-width="500">
                <img src="/resources/images/jazzy01.gif" class="leftHomeImage">
            </a>
            </div>
        </div>

        <div id="rightContent">
            <div class="rightContentContainerImage">
                <a href="/resources/images/jazzy02.gif" data-lightbox="jazzy01" title="My caption">
                    <img src="/resources/images/jazzy02.gif" class="rightHomeImage">
                </a>
            </div>
            <div class="rightContentContainerImage">
            <a href="/resources/images/jazzy02.gif" data-lightbox="jazzy01" title="My caption">
                <img src="/resources/images/jazzy02.gif" class="rightHomeImage">
            </a>
           </div>
        </div>
    </div>
    $constantAssets/footer()$
</div>
</body>
</body>
</html>
